/*
 * This code was generated by CalangoMDA (puppy) for use within the Prodepain
 * their products.The calangoMDA was created by Thiago Soares (tfs.capanema @
 * gmail.com)Â©CalangoDDA 2010
 */
package br.gov.pa.muiraquita.sample.rh.seam;

import java.util.List;

import org.jboss.seam.ScopeType;
import org.jboss.seam.annotations.Begin;
import org.jboss.seam.annotations.End;
import org.jboss.seam.annotations.In;
import org.jboss.seam.annotations.Name;
import org.jboss.seam.annotations.Out;
import org.jboss.seam.annotations.Scope;
import org.jboss.seam.annotations.datamodel.DataModel;
import org.jboss.seam.annotations.datamodel.DataModelSelection;
import org.jboss.seam.annotations.security.Restrict;

import br.gov.pa.muiraquita.sample.rh.dto.EstadoDto;
import br.gov.pa.muiraquita.sample.rh.dto.MunicipioDto;
import br.gov.pa.muiraquita.sample.rh.seam.factory.ApplicationFactorySeam;
import br.gov.pa.muiraquita.sample.rh.util.messages.SeamMessagesUtil;

@Name("estadoAction")
@Scope(ScopeType.CONVERSATION)
public class EstadoSeam extends RhAbstractSeam {

  @In(create = true, required = false)
  @Out(required = false)
  EstadoDto estadoDto;

  @DataModel
  List<EstadoDto> estadoDtoLista;

  @DataModelSelection("estadoDtoLista")
  EstadoDto estadoDtoSelecionado;
  
  @In(required = false, scope = ScopeType.APPLICATION)
  private ApplicationFactorySeam applicationFactory;

  private static final String START_PAGE = "/rh/estado/estado_list.xhtml";
  private static final String FORM_PAGE = "/rh/estado/estado_form.xhtml";
  private static final String UPDATE_PAGE = "/rh/estado/estado_update.xhtml";

  @Restrict("#{s:hasRole('0037000200001')}")
  @End(beforeRedirect = true)
  public String cadastrar() {
    try {
      getRhFacadeLocal().cadastrarEstado(this.estadoDto);
      this.estadoDto = new EstadoDto();
      
     // applicationFactory.reloadEstadoFactory();
      seamTreatment.addInfoMessage("O estado foi cadastrado com sucesso.");
    } catch (Throwable e) {
      log.info(this.getClass().getName() + ": Throwable: pilha:");
      seamTreatment.tratar(e);
    }
    return FORM_PAGE;
  }

  @Restrict("#{s:hasRole('0037000200002')}")
  @End(beforeRedirect = true)
  public String alterar() {
    try {
      getRhFacadeLocal().alterarEstado(this.estadoDto);
      
      this.showConfirmCadastro = true;
      applicationFactory.reloadEstadoFactory();
      seamTreatment.addInfoMessage("O estado foi alterado com sucesso.");
    } catch (Throwable e) {
      log.info(this.getClass().getName() + ": Throwable: pilha:");
      seamTreatment.tratar(e);
    }
    return START_PAGE;
  }

  @Restrict("#{s:hasRole('0037000200003')}")
  @Begin(join = true)
  public String buscar() {
    try {
      this.estadoDtoLista = getRhFacadeLocal().buscarEstados(this.estadoDto);
      seamTreatment.addInfoMessage(SeamMessagesUtil.getMessageForReturnList(this.estadoDtoLista));
    } catch (Throwable e) {
      log.info(this.getClass().getName() + ": Throwable: pilha:");
      seamTreatment.tratar(e);
    }
    return START_PAGE;
  }

  @Restrict("#{s:hasRole('0037000200004')}")
  @End(beforeRedirect = true)
  public void excluir() {
    try {
      getRhFacadeLocal().excluirEstado(this.estadoDto);
      seamTreatment.addInfoMessage("O estado foi excluído com sucesso.");
    } catch (Throwable e) {
      log.info(this.getClass().getName() + ": Throwable: pilha:");
      seamTreatment.tratar(e);
    }
  }

  @Begin(nested = true)
  public void selecionar() {
    this.estadoDto = this.estadoDtoSelecionado;
  }

  @Begin(nested = true)
  public String formConversation() {
    this.estadoDto = new EstadoDto();
    return FORM_PAGE;
  }
  
  @Begin(nested = true)
  public String updateConversation() {
    selecionar();
    return UPDATE_PAGE;
  }

  @End(beforeRedirect = true)
  public String backToSearch() {
    return START_PAGE;
  }
  
  @End(beforeRedirect = true, root = true)
  public String startConversation() {
    return START_PAGE;
  }

}