/*
 * This code was generated by CalangoMDA (puppy) for use within the Prodepain
 * their products.The calangoMDA was created by Thiago Soares (tfs.capanema @
 * gmail.com)Â©CalangoDDA 2010
 */
package br.gov.pa.muiraquita.sample.rh.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

import br.gov.pa.muiraquita.entity.AbstractEntity;

@Entity
@Table(name = "ESTADO", schema = "Rh")
public class Estado extends AbstractEntity {

  private static final long serialVersionUID = 1L;

  @Id
  @SequenceGenerator(name = "SQ_ESTADO", sequenceName = "rh.sq_estado", allocationSize = 1, initialValue = 1)
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SQ_ESTADO")
  @Column(name = "id", insertable = false, updatable = false)
  private Integer id;

  @NotNull(message = "Informe a descrição do estado")
  @Length(min = 1, max = 50, message = "A descrição do estado deve conter de {0} a {1} caracteres")
  @Column(name = "descricao")
  private String descricao;

  @NotNull(message = "Informe a sigla do estado")
  @Length(min = 2, max = 2, message = "A descrição do estado deve conter 2 caracteres")
  private String sigla;

  public Estado() {
    super();
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getId() {
    return id;
  }

  public void setDescricao(String descricao) {
    this.descricao = descricao;
  }

  public String getDescricao() {
    return descricao;
  }

  public void setSigla(String sigla) {
    this.sigla = sigla;
  }

  public String getSigla() {
    return sigla;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((descricao == null) ? 0 : descricao.hashCode());
    result = prime * result + ((id == null) ? 0 : id.hashCode());
    result = prime * result + ((sigla == null) ? 0 : sigla.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    Estado other = (Estado) obj;
    if (descricao == null) {
      if (other.descricao != null)
        return false;
    } else if (!descricao.equals(other.descricao))
      return false;
    if (id == null) {
      if (other.id != null)
        return false;
    } else if (!id.equals(other.id))
      return false;
    if (sigla == null) {
      if (other.sigla != null)
        return false;
    } else if (!sigla.equals(other.sigla))
      return false;
    return true;
  }
  
  

}