/* 
 *This code was generated by CalangoMDA (puppy) for use within the Prodepa 
 *in their products. 
 *The calangoMDA was created by Thiago Soares (tfs.capanema @ gmail.com) 
 *Â©CalangoDDA 2010 
 */ 
package br.gov.pa.muiraquita.sample.rh.business.error; 


 
import br.gov.pa.muiraquita.exception.retorno.retenum.ErrorCode;
import br.gov.pa.muiraquita.sample.rh.configuration.LocationsCDU;

 
public enum EstadoError implements ErrorCode { 


 	DESCRICAO_NULL(2, " Informe o/a descricao. "),
 	SIGLA_NULL(3, " Informe o/a sigla. "),
 	ESTADO_DUPLICATED(4, "Este estado já esta cadastrado."),
 	ESTADO_IMPEDIDO_EXCLUSAO(5, " O/A ESTADO nao pode ser excluido ."); 
  
	private String mensagemErro; 
 	private int codigo;  
 
 	private EstadoError(int codigo, String mensagemErro) {
 		this.codigo = codigo; 
 		this.mensagemErro = mensagemErro; 
 	} 
 
  public String getErrorMessage() { 
    return mensagemErro; 
  } 
  
  public int getCode() { 
    return codigo; 
  } 
 
  public String locateCode() { 
    return LocationsCDU.CDU_MANTER_BENEFICIO; 
  }  
 
}