/*
 * This code was generated by CalangoMDA (puppy) for use within the Prodepain
 * their products.The calangoMDA was created by Thiago Soares (tfs.capanema @
 * gmail.com)©CalangoDDA 2010
 */
package br.gov.pa.muiraquita.sample.rh.dao;

import java.util.List;

import br.gov.pa.muiraquita.exception.BusinessException;
import br.gov.pa.muiraquita.exception.InternalException;
import br.gov.pa.muiraquita.exception.SystemException;
import br.gov.pa.muiraquita.persistence.dao.IDao;
import br.gov.pa.muiraquita.sample.rh.dto.EstadoDto;
import br.gov.pa.muiraquita.sample.rh.entity.Estado;

/**
 * Interface declarativa de rotinas do Dao.
 */
public interface IEstadoDao extends IDao<Estado, Integer> {

  public List<Estado> findByParameters(EstadoDto estadoDto) throws SystemException, InternalException, BusinessException;
  
  public List<Estado> findForDuplications(EstadoDto parametros) throws SystemException, InternalException;

}