package br.com.capanema.kers.core.templates;

public class CopyrightTpl {

  private static final String conteudo = 
    "/* \n" +
    " *This code was generated by CalangoMDA (puppy) for use within the Prodepa \n" +
    " *in their products. \n" +
    " *The calangoMDA was created by Thiago Soares (tfs.capanema @ gmail.com) \n" +
    " *©CalangoDDA 2010 \n" +
    " */ \n";

  
  
  public static String getConteudo() {
    return conteudo;
  }
  
  @Override
  public String toString() {
    return conteudo;
  }
  
}


